name: Renovate Bot

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 5 * * *'

jobs:
  renovate-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: 1786773
          private-key: ${{ secrets.PRIVATE_KEY_GITHUB_APP_RENOVATE_BOT }}

      - name: Renovate Bot
        uses: renovatebot/github-action@v44.0.2
        with:
          configurationFile: renovate-config.js
          token: ${{ steps.app-token.outputs.token }}
